# Generated by Django 5.1.15 on 2026-07-19 20:47

import datetime
import django.db.models.deletion
import gate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(default='Gatepass Leisure Park', max_length=120)),
                ('venue_city', models.CharField(default='Harare', max_length=80)),
                ('zig_per_usd', models.DecimalField(decimal_places=2, default=30, max_digits=12)),
                ('closing_time', models.TimeField(default=datetime.time(18, 0))),
            ],
            options={
                'verbose_name': 'Gate settings',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('emoji', models.CharField(default='🎟️', max_length=8)),
                ('adult_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overstay_rate_usd', models.DecimalField(decimal_places=2, default=2, help_text='Charged per started 30 minutes past expiry (whole party).', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'adult_price_usd'],
            },
        ),
        migrations.CreateModel(
            name='TimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('minutes', models.PositiveIntegerField(blank=True, help_text='Blank = full day (expires at closing time).', null=True)),
                ('active', models.BooleanField(default=True)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, default=gate.models._number, max_length=16, unique=True)),
                ('qr_token', models.CharField(default=gate.models._token, max_length=64, unique=True)),
                ('duration_label', models.CharField(max_length=40)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('visitor_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('vehicle_reg', models.CharField(blank=True, max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold (ZiG)')], default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ECOCASH', 'EcoCash'), ('ONEMONEY', 'OneMoney'), ('INNBUCKS', 'InnBucks'), ('OMARI', "O'mari"), ('ZIPIT', 'ZimSwitch'), ('CARD', 'Visa / Mastercard')], default='CASH', max_length=12)),
                ('zig_per_usd', models.DecimalField(decimal_places=2, default=30, max_digits=12)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXITED', 'Exited'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('overstay_fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overstay_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overstay_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ECOCASH', 'EcoCash'), ('ONEMONEY', 'OneMoney'), ('INNBUCKS', 'InnBucks'), ('OMARI', "O'mari"), ('ZIPIT', 'ZimSwitch'), ('CARD', 'Visa / Mastercard')], max_length=12)),
                ('issued_by', models.CharField(blank=True, max_length=80)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='gate.package')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
