# Generated by Django 5.1.15 on 2026-07-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='fixed_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='FIXED only: locked duration (e.g. 180 for Play & Movie). Blank = valid until closing time.', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='group',
            field=models.CharField(default='General', max_length=40),
        ),
        migrations.AddField(
            model_name='package',
            name='pricing',
            field=models.CharField(choices=[('HOURLY', 'Per hour'), ('FIXED', 'Flat price')], default='FIXED', max_length=8),
        ),
        migrations.AlterField(
            model_name='gateconfig',
            name='venue_name',
            field=models.CharField(default='Max Fun Entertainment', max_length=120),
        ),
    ]
