# Generated by Django 5.1.15 on 2026-07-27 12:37

import django.db.models.deletion
import django.utils.timezone
import gate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_package_fixed_minutes_package_group_package_pricing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wristband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.AddField(
            model_name='gateconfig',
            name='gateway_key',
            field=models.CharField(default=gate.models._token, help_text='Shared secret BLE gateways send as X-Gateway-Key.', max_length=64),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('CASHIER', 'Gate cashier'), ('SECURITY', 'Security')], default='CASHIER', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BandAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=120)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='gate.ticket')),
                ('wristband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gate.wristband')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(blank=True, max_length=64)),
                ('seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('wristband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='gate.wristband')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='gate.zone')),
            ],
            options={
                'ordering': ['-seen_at'],
            },
        ),
    ]
